### ISSUE TITLE
博客生成却无法发布，generate blog successfully but got error on deploy blog

### ISSUE THREAD

**Issue by suredream** [Meekdai/Gmeek#244]
Appreciated if any idea, pretty close.

<img width="1212" alt="Image" src="https://github.com/user-attachments/assets/a25ed2b5-47fc-4b46-b1a3-97e4dd4aa753" />

**Comment by suredream** [comment]
问题已解决，我的Gmeek.yml 太老了，更新一下到

```
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```

就可以
